select user
from dual;

drop table tbl_memberlist;

--테이블 구성
CREATE TABLE TBL_MEMBERLIST
(MID NUMBER
, NAME VARCHAR2(30)
, TELEPHONE VARCHAR2(40)
, CONSTRAINT MEMBERLIST_MID_PK PRIMARY KEY(MID)
);

--기존 시퀀스 제거
drop SEQUENCE MEMBERLISTSEQ;

--시퀀스 생성
CREATE SEQUENCE MEMBERLISTSEQ
NOCACHE;

--데이터 입력
INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE)
VALUES(MEMBERLISTSEQ.NEXTVAL, '장진하', '010-1111-1111');

--조회
SELECT MID, NAME, TELEPHONE
FROM TBL_MEMBERLIST
ORDER BY MID;

COMMIT;

--인원 수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERLIST;

--데이터 추가 입력
INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE)
VALUES(MEMBERLISTSEQ.NEXTVAL, '김소연', '010-2222-2222');

COMMIT;




